/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recording */
        post: operations["create_recording_api_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append Event */
        post: operations["append_event_api_recordings__recording_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Recording */
        post: operations["finalize_recording_api_recordings__recording_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_api_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guides */
        get: operations["list_guides_api_guides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guides/{guide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Guide */
        get: operations["get_guide_api_guides__guide_id__get"];
        put?: never;
        post?: never;
        /** Delete Guide */
        delete: operations["delete_guide_api_guides__guide_id__delete"];
        options?: never;
        head?: never;
        /** Patch Guide */
        patch: operations["patch_guide_api_guides__guide_id__patch"];
        trace?: never;
    };
    "/api/guides/{guide_id}/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Step */
        delete: operations["delete_step_api_guides__guide_id__steps__step_id__delete"];
        options?: never;
        head?: never;
        /** Patch Step */
        patch: operations["patch_step_api_guides__guide_id__steps__step_id__patch"];
        trace?: never;
    };
    "/api/guides/{guide_id}/steps:reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Steps */
        post: operations["reorder_steps_api_guides__guide_id__steps_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guides/{guide_id}/steps/{step_id}:regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Step */
        post: operations["regenerate_step_api_guides__guide_id__steps__step_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshots/{screenshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screenshot */
        get: operations["get_screenshot_api_screenshots__screenshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guides/{guide_id}/export/markdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Markdown */
        get: operations["export_markdown_api_guides__guide_id__export_markdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BBox
         * @description Element bounding box, normalized to the viewport (0..1 fractions).
         */
        BBox: {
            /** Nx */
            nx: number;
            /** Ny */
            ny: number;
            /** Nw */
            nw: number;
            /** Nh */
            nh: number;
        };
        /** Body_append_event_api_recordings__recording_id__events_post */
        Body_append_event_api_recordings__recording_id__events_post: {
            /** Event */
            event: string;
            /** Screenshot */
            screenshot?: string | null;
        };
        /**
         * ClickPoint
         * @description Click position as viewport fractions; raw client coords kept for forensics.
         */
        ClickPoint: {
            /** Nx */
            nx: number;
            /** Ny */
            ny: number;
            /** Clientx */
            clientX?: number | null;
            /** Clienty */
            clientY?: number | null;
            bbox?: components["schemas"]["BBox"] | null;
        };
        /** ElementMeta */
        ElementMeta: {
            /**
             * Tag
             * @default
             */
            tag: string;
            /** Text */
            text?: string | null;
            /** Arialabel */
            ariaLabel?: string | null;
            /** Placeholder */
            placeholder?: string | null;
            /** Name */
            name?: string | null;
            /** Id */
            id?: string | null;
            /** Role */
            role?: string | null;
            /** Type */
            type?: string | null;
            /** Href */
            href?: string | null;
            /** Alt */
            alt?: string | null;
            /** Selector */
            selector?: string | null;
            /** Region */
            region?: string | null;
        };
        /** EventAccepted */
        EventAccepted: {
            /** Seq */
            seq: number;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
        /** FinalizeResponse */
        FinalizeResponse: {
            /** Guideid */
            guideId: string;
        };
        /** GuideOut */
        GuideOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** GuidePatch */
        GuidePatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
        };
        /** GuideSummary */
        GuideSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Stepcount */
            stepCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** RecordingCreated */
        RecordingCreated: {
            /** Id */
            id: string;
        };
        /** RecordingStatus */
        RecordingStatus: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "recording" | "finalizing" | "finalized" | "abandoned";
            /** Eventcount */
            eventCount: number;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt?: string | null;
            /** Guideid */
            guideId?: string | null;
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /** Stepids */
            stepIds: string[];
        };
        /** StepMeta */
        StepMeta: {
            /**
             * Url
             * @default
             */
            url: string;
            /** Ts */
            ts?: number | null;
            /** Eventtype */
            eventType?: ("click" | "type" | "navigate") | null;
            /** Elementlabel */
            elementLabel?: string | null;
            /** Region */
            region?: string | null;
            element?: components["schemas"]["ElementMeta"] | null;
            typed?: components["schemas"]["TypedValue"] | null;
        } & {
            [key: string]: unknown;
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Screenshotid */
            screenshotId?: string | null;
            /** Instructiontext */
            instructionText: string;
            /**
             * Instructionoverridden
             * @default false
             */
            instructionOverridden: boolean;
            /** Callouttype */
            calloutType?: ("info" | "warning" | "caution") | null;
            /** Callouttext */
            calloutText?: string | null;
            click?: components["schemas"]["ClickPoint"] | null;
            meta: components["schemas"]["StepMeta"];
        };
        /**
         * StepPatch
         * @description Partial update; only fields present in the request are applied.
         */
        StepPatch: {
            /** Instructiontext */
            instructionText?: string | null;
            /** Callouttype */
            calloutType?: ("info" | "warning" | "caution") | null;
            /** Callouttext */
            calloutText?: string | null;
            click?: components["schemas"]["ClickPoint"] | null;
            /**
             * Clearcallout
             * @default false
             */
            clearCallout: boolean;
        };
        /** TypedValue */
        TypedValue: {
            /**
             * Value
             * @default
             */
            value: string;
            /**
             * Masked
             * @default false
             */
            masked: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_recording_api_recordings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingCreated"];
                };
            };
        };
    };
    append_event_api_recordings__recording_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_append_event_api_recordings__recording_id__events_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_recording_api_recordings__recording_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_guides_api_guides_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideSummary"][];
                };
            };
        };
    };
    get_guide_api_guides__guide_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_guide_api_guides__guide_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_guide_api_guides__guide_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuidePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_step_api_guides__guide_id__steps__step_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_step_api_guides__guide_id__steps__step_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_steps_api_guides__guide_id__steps_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_step_api_guides__guide_id__steps__step_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screenshot_api_screenshots__screenshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screenshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_markdown_api_guides__guide_id__export_markdown_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                guide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
